### PR TITLE
Update app.js

### PR DESCRIPTION
**Pull request by thebrownfox**
There is conflict with angular-animate due to different versions in angular-base-apps.
Edit: Angular and Angular-animate have to be of the same version, which is already in angular-base-apps.
Edit2: ` Uncaught Error: [$injector:unpr] Unknown provider: $$forceReflowProvider <- $$forceReflow <- $$animateQueue <- $animate <- $compile <- $$animateQueue `

`

### CODE REVIEW

**Comment by soumak77** [comment]
This change breaks the build.  The correct solution would be to update angular-base-apps to fix this versioning issue.

**Comment by soumak77** [comment]
@jasterba I just published a [new version](https://github.com/base-apps/angular-base-apps/releases/tag/v2.0.10) of angular-base-apps which adds support for angular 1.6.x.  Give that a try and let me know if it fixes your issues.

**Comment by thebrownfox** [comment]
@soumak77 Is it necessary to bring another angular package, when there is one in angular-base-apps already? That can only break things, right?

**Comment by soumak77** [comment]
The update to the version numbers should make it so that npm will use the same angular version as your project's package.json.  I suspect you are using angular 1.6.x?

**Comment by thebrownfox** [comment]
I mean there is angular dependency in package.json, while there is already angular in base apps. Do you need to install separate angular package and then import it over the angular from the base apps? My point was to make it dependand only on one (base) package that won't break anything.

**Comment by soumak77** [comment]
Prior to making my change earlier, the angular version specified in the project **"^1.5.8"** resolved to angular 1.6.x.  Angular base apps at the time was only specified that it could support angular **"1.3.x - 1.5.x"** and therefore had to download it's own local version.  Once I changed this to **"1.3.x - 1.6.x"**, the local copy of angular was no longer needed as it could use the angular version specified by the project.

**Pull request closed without merging**
